spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socialNetwork?serverTimezone=UTC
    password: root
    initialization-mode: always
    username: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  thymeleaf:
    cache: false
server:
  port: 8070